# Generated by Django 2.2.3 on 2019-07-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='pic_folder/no-img.jpg', upload_to='pic_folder/')),
                ('rank', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.CharField(max_length=4)),
                ('country', models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('DECEMBER', 'December')], default='(-_-)', max_length=30)),
                ('time', models.DateField(auto_now_add=True)),
                ('genre1', models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('DECEMBER', 'December')], max_length=30)),
                ('genre2', models.CharField(blank=True, choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('DECEMBER', 'December')], max_length=30)),
                ('genre3', models.CharField(blank=True, choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('DECEMBER', 'December')], max_length=30)),
            ],
        ),
    ]
