# Generated by Django 2.2.3 on 2019-07-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='long',
            field=models.CharField(default='', max_length=4),
        ),
    ]
