# Generated by Django 2.2.3 on 2019-07-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='serial',
            field=models.BooleanField(default=False),
        ),
    ]
