# Generated by Django 2.2.3 on 2019-07-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movie_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
