# Generated by Django 2.2.3 on 2019-07-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190726_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(choices=[('Канада', 'Канада'), ('Россия', 'Россия'), ('Великобритания', 'Великобритания'), ('США', 'США'), ('Австралия', 'Австралия'), ('Бельгия', 'Бельгия'), ('Бразилия', 'Бразилия'), ('Германия', 'Германия'), ('Ирландия', 'Ирландия'), ('Испания', 'Испания'), ('Италия', 'Италия'), ('Мексика', 'Мексика'), ('Франция', 'Франция'), ('Япония', 'Япония'), ('Другая', 'Другая')], default='(-_-)', max_length=30),
        ),
    ]
